[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"


[project]
name = "qcl-image-analysis"
version = "0.1.0"
description = "Tools for processing and analyzing QCL microscopy images."

requires-python = ">=3.12,<3.13"

dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "matplotlib",
    "pyyaml",
]


[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

notebook = [
    "ipykernel",
    "ipympl",
    "ipywidgets",
]

[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
testpaths = ["tests"]


[tool.ruff]
line-length = 88
target-version = "py312"