/* Local processing controller. Filename-derived spectral roles are explicit;
 * canvas rectangles share image-pixel coordinates across processing stages.
 * Changes lock dependent steps until the corresponding API operation succeeds.
 * Heatmap contrast affects rendering only, never the scientific arrays. */
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const stages=['raw','reflectance','fourier','rolling','absorbance','baseline'];
const stageNames=['Raw 强度','处理前反射率','Fourier 后反射率','Rolling ball 后反射率','基线校正前吸光度','基线校正后吸光度'];
const titles=['导入数据','配置中心与参考波数','框选 on-MS 区域','Fourier 与平场校正','选择 cell-free 区域','处理结果与 CNR'];
const state={step:1,maxStep:1,discovery:null,mapping:{},patterns:[],bands:[],qc:[],rois:{on:null,r0:null,background:null,target:null},cnr:[],cnrDirty:false,r0:[],canvases:[],mode:null,version:0,viewEpoch:0,time:null,timer:null};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function notify(text,error=false){const n=$('#notice');n.hidden=false;n.textContent=text;n.className=error?'error':''}
async function api(path,payload){const r=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw Error(data.error||'操作失败');return data}
async function busy(button,fn){if(document.body.classList.contains('busy'))return;document.body.classList.add('busy');const old=button.textContent;button.textContent='处理中…';notify('正在本地计算，请稍候。多图或较大的 rolling-ball 半径需要更长时间。');try{await fn()}catch(e){notify(e.message,true)}finally{document.body.classList.remove('busy');button.textContent=old}}
function unlock(n){state.maxStep=n;renderNav()}
function renderNav(){const nav=$('#navigation');nav.replaceChildren();titles.forEach((t,i)=>{const b=el('button',undefined,state.step===i+1?'active':'');b.append(el('i',String(i+1)));const label=el('span',t);b.append(label);b.disabled=i+1>state.maxStep;b.onclick=()=>go(i+1);nav.append(b)})}
function invalidateFrom(n){state.maxStep=Math.min(state.maxStep,n-1);state.cnr=[];state.rois.background=state.rois.target=null;clearInterval(state.timer);state.timer=null;$('#time-player').hidden=true;renderNav()}
function go(step){if(step>state.maxStep)return;state.step=step;$$('section[data-step]').forEach(n=>n.hidden=+n.dataset.step!==step);$('#page-title').textContent=titles[step-1];$('#preview-controls').hidden=step<3;renderNav();refreshView().catch(e=>notify(e.message,true));window.scrollTo({top:0,behavior:'smooth'})}
function fillSelect(node,values,preferred){node.replaceChildren();for(const v of values){const o=el('option',String(v));o.value=v;node.append(o)}if(values.map(String).includes(String(preferred)))node.value=preferred}
function updatePreview(){fillSelect($('#preview-pattern'),state.patterns,$('#preview-pattern').value);fillSelect($('#preview-band'),state.bands,Object.keys(state.mapping)[0]);}
function checkbox(value,checked,callback){const label=el('label',undefined,'chip');const input=el('input');input.type='checkbox';input.value=value;input.checked=checked;input.onchange=()=>callback(input.checked);label.append(input,document.createTextNode(String(value)));return label}
function involved(){return [...new Set([...Object.keys(state.mapping).map(Number),...Object.values(state.mapping).flat()])].sort((a,b)=>a-b)}
function renderMapping(){const root=$('#reference-mapping');root.replaceChildren();for(const center of Object.keys(state.mapping).map(Number).sort((a,b)=>a-b)){const row=el('div',undefined,'mapping-row');row.append(el('h3',`${center} cm⁻¹ 的基线参考`));const chips=el('div',undefined,'chips');for(const wn of state.discovery.wavenumbers){if(wn===center)continue;chips.append(checkbox(wn,state.mapping[center].includes(wn),checked=>{state.mapping[center]=checked?[...state.mapping[center],wn].sort((a,b)=>a-b):state.mapping[center].filter(v=>v!==wn);mappingChanged()}))}row.append(chips);root.append(row)}mappingChanged()}
function mappingChanged(){invalidateFrom(3);const wns=involved();$('#involved-bands').textContent=wns.length?`将处理全部涉及波数：${wns.join(' · ')} cm⁻¹`:'请选择中心与参考波数。';renderPatterns()}
function renderPatterns(){const root=$('#pattern-options');const previous=new Set($$('input[data-pattern]:checked').map(n=>n.value));const initial=!root.children.length;root.replaceChildren();const required=involved();for(const [index,p] of state.discovery.availability.entries()){const missing=required.filter(w=>!p.wavenumbers.includes(w));const label=el('label',undefined,'pattern');const input=el('input');input.type='checkbox';input.dataset.pattern='true';input.value=p.pattern;input.disabled=missing.length>0;input.checked=!missing.length&&(previous.has(p.pattern)||(initial&&index===0));input.onchange=()=>invalidateFrom(3);label.append(input,document.createTextNode(p.pattern),el('small',missing.length?`缺少 ${missing.join(', ')}`:`${p.wavenumbers.length} 个波数`));root.append(label)}}
$('#discover').onclick=()=>busy($('#discover'),async()=>{const d=await api('/api/discover',{path:$('#input-path').value});state.discovery=d;state.mapping={};state.patterns=[];state.bands=[];state.version=d.version;$('#center-options').replaceChildren();$('#pattern-options').replaceChildren();$('#reference-mapping').replaceChildren();for(const wn of d.wavenumbers)$('#center-options').append(checkbox(wn,false,on=>{if(on)state.mapping[wn]=[];else delete state.mapping[wn];renderMapping()}));$('#discovered-bands').replaceChildren(...d.wavenumbers.map(w=>el('span',`${w} cm⁻¹`,'chip')));$('#discovery-count').textContent=`${d.files} 张图像 · ${d.availability.length} 个 patterns`;$('#discovery-summary').hidden=false;renderPatterns();unlock(2);localStorage.setItem('qclProcessingPath',$('#input-path').value);$('#session-status').textContent=`已识别 ${d.wavenumbers.length} 个波数`;notify('波数已从文件名自动识别。请手动选择中心及各自的基线参考。');go(2)});
$('#select-complete').onclick=()=>{$$('input[data-pattern]').forEach(n=>n.checked=!n.disabled);invalidateFrom(3)};
$('#configure').onclick=()=>busy($('#configure'),async()=>{const d=await api('/api/configure',{mapping:state.mapping,patterns:$$('input[data-pattern]:checked').map(n=>n.value),n_pixels:+$('#reference-pixels').value,robust_z_threshold:+$('#qc-z').value,relative_threshold:+$('#qc-deviation').value});Object.assign(state,{mapping:d.mapping,patterns:d.patterns,bands:d.bands,qc:d.qc,version:d.version,cnr:[],cnrDirty:false,r0:[]});state.rois={on:null,r0:null,background:null,target:null};state.cnrDirty=false;updatePreview();unlock(3);const frames=d.qc.map(r=>r.frame);$('#time-start').value=Math.min(...frames);$('#time-end').value=Math.max(...frames);$('#session-status').textContent=`${d.patterns.length} patterns · ${d.bands.length} 波数`;notify('配置已确认。所有涉及波数均已独立归一化。');go(3)});
function coords(name){const root=$(`#${name==='on'?'on':'r0'}-coordinates`);root.replaceChildren();const roi=state.rois[name];for(const key of ['x_min','x_max','y_min','y_max']){const label=el('label',key.replace('_',' ')),input=el('input');input.type='number';input.min=0;input.value=roi?roi[key]:'';input.oninput=()=>{if(!state.rois[name])state.rois[name]={x_min:0,x_max:0,y_min:0,y_max:0};state.rois[name][key]=+input.value;invalidateFrom(name==='on'?4:6);drawAll()};label.append(input);root.append(label)}}
function imageParams(kind){return {pattern:$('#preview-pattern').value,wavenumber:$('#preview-band').value,kind,low:$('#display-low').value,high:$('#display-high').value,version:state.version}}
async function heatmap(root,kind,title,roiName=null,epoch=state.viewEpoch){const card=el('div',undefined,'image-card');card.append(el('h4',title));root.append(card);const params=imageParams(kind);if(kind==='full_raw')params.brightest='true';if(kind==='spectrum')params.window=String($('#inspection-window').checked);const data=await api('/api/image?'+new URLSearchParams(params));if(epoch!==state.viewEpoch)return;if(!data.available){card.append(el('div',kind==='baseline'?'此波数仅作为参考，未设置基线中心':'完成后续步骤后可用','placeholder'));return}const wrap=el('div',undefined,'heatmap'),canvas=el('canvas');canvas.width=data.width;canvas.height=data.height;wrap.append(canvas);const bar=el('div',undefined,'bar'),strip=el('div',undefined,'strip'),ticks=el('div',undefined,'ticks');[data.vmax,(data.vmax+data.vmin)/2,data.vmin].forEach(v=>ticks.append(el('span',Number(v.toPrecision(4)).toString())));bar.append(strip,ticks);wrap.append(bar);card.append(wrap);if(kind==='spectrum')card.append(el('div','fx: −0.5 → +0.5; fy: −0.5 (top) → +0.5 (bottom)','axis-hint'));const image=new Image;image.src='data:image/png;base64,'+data.png;await image.decode();if(epoch!==state.viewEpoch)return;const view={canvas,image,data,kind,roiName,titleNode:card.querySelector('h4'),title};state.canvases.push(view);bindCanvas(view);draw(view)}
function draw(v){const ctx=v.canvas.getContext('2d');ctx.clearRect(0,0,v.canvas.width,v.canvas.height);ctx.drawImage(v.image,0,0,v.canvas.width,v.canvas.height);const pairs=v.roiName==='cnr'?[['background','#00eaff'],['target','#7dff00']]:v.roiName?[[v.roiName,'#00eaff']]:[];for(const [name,color] of pairs){const r=state.rois[name];if(!r)continue;ctx.strokeStyle=color;ctx.lineWidth=Math.max(v.data.width/400,.6);ctx.strokeRect(r.x_min,r.y_min,r.x_max-r.x_min,r.y_max-r.y_min)}if(v.roiName==='cnr'){const row=state.cnr.find(r=>r.pattern===$('#preview-pattern').value&&r.wavenumber===+$('#preview-band').value&&r.stage===v.kind);v.titleNode.textContent=v.title+(row?` · CNR ${row.cnr===null?'不可用':row.cnr.toFixed(3)}`:'')}}
function drawAll(){state.canvases.forEach(draw)}
function bindCanvas(v){let start=null;const point=e=>{const b=v.canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(v.data.width,(e.clientX-b.left)*v.data.width/b.width)),y:Math.max(0,Math.min(v.data.height,(e.clientY-b.top)*v.data.height/b.height))}};v.canvas.onpointerdown=e=>{if(document.body.classList.contains('busy'))return;if(v.kind==='spectrum'){if($('#filter-mode').value!=='notch')return;const p=point(e);const fx=v.data.fx[Math.min(v.data.width-1,Math.floor(p.x))],fy=v.data.fy[Math.min(v.data.height-1,Math.floor(p.y))];$('#notches').value+=($('#notches').value.trim()?'; ':'')+`${fy.toFixed(6)}, ${fx.toFixed(6)}`;invalidateFrom(5);return}if(!v.roiName)return;if(v.roiName==='cnr'&&!state.mode)return;start=point(e);v.canvas.setPointerCapture(e.pointerId)};const update=e=>{if(!start)return;const p=point(e),name=v.roiName==='cnr'?state.mode:v.roiName;state.rois[name]={x_min:Math.floor(Math.min(start.x,p.x)),x_max:Math.ceil(Math.max(start.x,p.x)),y_min:Math.floor(Math.min(start.y,p.y)),y_max:Math.ceil(Math.max(start.y,p.y))};if(name==='on'||name==='r0'){invalidateFrom(name==='on'?4:6);coords(name)}else{state.cnr=[];if(name==='background')state.rois.target=null;$('#cnr-table').replaceChildren();chart($('#cnr-chart'),[])}drawAll()};v.canvas.onpointermove=update;v.canvas.onpointerup=e=>{update(e);start=null};v.canvas.onpointercancel=()=>start=null}
async function refreshView(){clearInterval(state.timer);state.timer=null;if(state.step<3)return;const epoch=++state.viewEpoch;state.canvases=[];if(state.step===3){$('#crop-preview').replaceChildren();coords('on');await heatmap($('#crop-preview'),$('#raw-view').value,'全幅图像','on',epoch);table($('#qc-table'),state.qc,['pattern','wavenumber','i_goldref','reference_valid','frame_valid']);chart($('#qc-chart'),state.bands.map(wn=>({name:String(wn),values:state.qc.filter(r=>r.wavenumber===wn).map(r=>r.i_goldref)})))}if(state.step===4){$('#spectrum-preview').replaceChildren();await heatmap($('#spectrum-preview'),'spectrum','检查频谱 · 点击添加陷波位置',null,epoch)}if(state.step===5){$('#r0-preview').replaceChildren();$('#processing-preview').replaceChildren();coords('r0');await heatmap($('#r0-preview'),'rolling','Rolling ball 校正后反射率','r0',epoch);await Promise.all(['reflectance','fourier','rolling'].map((kind,i)=>heatmap($('#processing-preview'),kind,['处理前','Fourier 后','Rolling ball 后'][i],null,epoch)))}if(state.step===6){$('#six-stages').replaceChildren();await Promise.all(stages.map((kind,i)=>heatmap($('#six-stages'),kind,stageNames[i],'cnr',epoch)));showCNR();table($('#r0-table'),state.r0,['pattern','wavenumber','r0','reference_mean_absorbance'])}}
$('#confirm-crop').onclick=()=>busy($('#confirm-crop'),async()=>{if(!state.rois.on)throw Error('请先框选 on-MS 区域。');const d=await api('/api/crop',{roi:state.rois.on});state.version=d.version;state.rois.r0=state.rois.background=state.rois.target=null;unlock(4);notify('共享 on-MS 裁剪已确认。');go(4)});
function filterMode(){const mode=$('#filter-mode').value;$$('[data-filter]').forEach(n=>n.hidden=n.dataset.filter!==mode)}
$('#filter-mode').onchange=()=>{filterMode();invalidateFrom(5)};
$('#clear-notches').onclick=()=>{$('#notches').value='';invalidateFrom(5)};
function notchCenters(){const text=$('#notches').value.trim();if(!text)return[];return text.split(/[;\n]+/).filter(s=>s.trim()).map(s=>{const pair=s.split(',').map(v=>Number(v.trim()));if(pair.length!==2||pair.some(v=>!Number.isFinite(v)))throw Error('陷波中心格式应为 fy, fx；用分号分隔多组。');return pair})}
$('#process').onclick=()=>busy($('#process'),async()=>{const mode=$('#filter-mode').value;const fourier={mode,centers:mode==='notch'?notchCenters():[],sigma:+$('#notch-sigma').value,strength:+$('#notch-strength').value,protect_radius:+$('#protect-radius').value,cutoff_x:+$('#cutoff-x').value,cutoff_y:+$('#cutoff-y').value,pad_pixels:+$('#fourier-pad').value,preserve_mean:true};const rolling={radius:+$('#rb-radius').value,kernel_height:+$('#rb-height').value,feature_polarity:$('#rb-polarity').value,smooth_sigma:+$('#rb-sigma').value,pad_pixels:+$('#rb-pad').value,min_background:1e-6,reference_level:null};const d=await api('/api/process',{fourier,rolling});state.version=d.version;state.rois.r0=state.rois.background=state.rois.target=null;state.r0=[];unlock(5);notify(`已完成 ${d.summary.length} 张图像的 Fourier 和 rolling-ball 处理。`);go(5)});
$('#calculate').onclick=()=>busy($('#calculate'),async()=>{if(!state.rois.r0)throw Error('请先框选 cell-free ROI。');const d=await api('/api/calculate',{roi:state.rois.r0});state.version=d.version;state.r0=d.r0;state.cnr=[];state.rois.background=state.rois.target=null;state.mode=null;state.cnrDirty=false;unlock(6);notify('所有涉及波数已计算吸光度；全部中心波数已完成基线校正。');go(6)});
$('#cnr-background').onclick=()=>{state.cnrDirty=true;state.mode='background';state.rois.background=state.rois.target=null;state.cnr=[];showCNR();$('#cnr-instruction').textContent='正在选择 background：在任意阶段拖动矩形。';drawAll()};
$('#cnr-target').onclick=()=>{if(!state.rois.background){notify('请先选择 background。',true);return}state.cnrDirty=true;state.mode='target';state.rois.target=null;state.cnr=[];showCNR();$('#cnr-instruction').textContent='正在选择目标 ROI：与 background 不可重叠。';drawAll()};
$('#calculate-cnr').onclick=()=>busy($('#calculate-cnr'),async()=>{if(!state.rois.background||!state.rois.target)throw Error('请先依次选择 background 和目标 ROI。');const d=await api('/api/cnr',{background:state.rois.background,target:state.rois.target});state.cnr=d.records;state.cnrDirty=false;state.mode=null;drawAll();showCNR();notify('已使用同一套 ROI 计算所有 patterns、波数和阶段的 CNR。')});
function fmt(v){if(v===null||v===undefined)return'—';if(typeof v==='number')return Number(v.toPrecision(6)).toString();return String(v)}
function table(root,rows,keys){root.replaceChildren();if(!rows.length){root.append(el('p','暂无结果','hint'));return}const t=el('table'),head=el('thead'),tr=el('tr');keys.forEach(k=>tr.append(el('th',k)));head.append(tr);const body=el('tbody');rows.forEach(r=>{const row=el('tr');keys.forEach(k=>row.append(el('td',fmt(r[k]))));body.append(row)});t.append(head,body);root.append(t)}
function chart(canvas,series,labels=[]){const ctx=canvas.getContext('2d'),ratio=devicePixelRatio||1,w=canvas.clientWidth||600,h=240;canvas.width=w*ratio;canvas.height=h*ratio;ctx.scale(ratio,ratio);ctx.clearRect(0,0,w,h);const finite=series.flatMap(s=>s.values).filter(v=>v!==null&&Number.isFinite(v));if(!finite.length){ctx.fillStyle='#829389';ctx.fillText('计算后显示趋势',20,35);return}const low=Math.min(...finite),high=Math.max(...finite),span=high-low||1,p={l:55,r:20,t:30,b:48},colors=['#157e69','#b6803b','#6473a1','#995477'];ctx.font='10px sans-serif';for(let i=0;i<4;i++){const y=p.t+(h-p.t-p.b)*i/3;ctx.strokeStyle='#e4eae5';ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillStyle='#708477';ctx.fillText(fmt(high-span*i/3).slice(0,7),4,y+3)}series.forEach((s,index)=>{const color=colors[index%colors.length],n=s.values.length;ctx.strokeStyle=color;ctx.lineWidth=1.8;ctx.beginPath();let connect=false;s.values.forEach((v,i)=>{if(v===null||!Number.isFinite(v)){connect=false;return}const x=p.l+(w-p.l-p.r)*i/Math.max(1,n-1),y=p.t+(h-p.t-p.b)*(high-v)/span;if(connect)ctx.lineTo(x,y);else ctx.moveTo(x,y);connect=true});ctx.stroke();ctx.fillStyle=color;ctx.fillText(s.name,p.l+index*110,15)});labels.forEach((s,i)=>{ctx.fillStyle='#708477';ctx.fillText(s,p.l+(w-p.l-p.r)*i/Math.max(1,labels.length-1)-15,h-15)})}
function showCNR(){const rows=state.cnr.filter(r=>r.pattern===$('#preview-pattern').value&&r.wavenumber===+$('#preview-band').value);table($('#cnr-table'),rows,['stage','cnr','target_mean','background_mean','background_std','target_pixels','background_pixels','status']);chart($('#cnr-chart'),rows.length?[{name:'CNR',values:rows.map(r=>r.cnr)}]:[],['Raw','R before','Fourier','Rolling','A before','A baseline'])}
$('#build-time').onclick=()=>busy($('#build-time'),async()=>{state.time=await api('/api/timelapse',{wavenumber:+$('#preview-band').value,kind:$('#time-kind').value,start:+$('#time-start').value,end:+$('#time-end').value,skip_invalid:$('#time-skip').checked});$('#time-player').hidden=false;$('#time-slider').max=state.time.frames.length-1;$('#time-slider').value=0;renderFrame();notify(`已生成 ${state.time.frames.length} 帧，所有帧使用同一色阶。`)});
function renderFrame(){const i=+$('#time-slider').value,f=state.time.frames[i];$('#time-image').src='data:image/png;base64,'+f.png;$('#time-label').textContent=`${f.pattern} · ${i+1}/${state.time.frames.length} · 经过 ${f.elapsed_seconds.toFixed(1)} s · ${new Date(f.timestamp*1000).toLocaleString()} · dt 中位数 ${state.time.median_interval_seconds.toFixed(1)} s`}
$('#time-slider').oninput=()=>{if(state.time)renderFrame()};$('#time-play').onclick=()=>{if(state.timer){clearInterval(state.timer);state.timer=null;return}if(!state.time)return;state.timer=setInterval(()=>{$('#time-slider').value=(+$('#time-slider').value+1)%state.time.frames.length;renderFrame()},1000/Math.max(1,+$('#time-fps').value))};
for(const id of ['preview-pattern','preview-band','raw-view','inspection-window'])$(`#${id}`).onchange=()=>refreshView().catch(e=>notify(e.message,true));
$('#refresh-view').onclick=()=>refreshView().catch(e=>notify(e.message,true));
$$('[data-go]').forEach(b=>b.onclick=()=>go(+b.dataset.go));
$$('section[data-step="4"] input, section[data-step="4"] textarea, #rb-polarity').forEach(n=>{if(n.id!=='inspection-window')n.addEventListener('change',()=>invalidateFrom(5))});
for(const id of ['reference-pixels','qc-z','qc-deviation'])$(`#${id}`).onchange=()=>invalidateFrom(3);
$('#input-path').value=localStorage.getItem('qclProcessingPath')||'';
renderNav();filterMode();

// Do not export an older CNR measurement after its visible ROIs are edited.
$('#download').onclick=e=>{if(state.cnrDirty||((state.rois.background||state.rois.target)&&!state.cnr.length)){e.preventDefault();notify('ROI 已改变，请重新计算 CNR 后再导出。',true)}};
